kube-prometheus-stack:

  alertmanager:
    enabled: false

  grafana:
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      enabled: true
      ingressClassName: nginx-public
      hosts:
        - grafana.alix.lol
      path: /
      tls:
      - secretName: grafana-tls
        hosts:
        - grafana.alix.lol
    serviceMonitor:
      additionalLabels:
        prometheus: prometheus

  prometheus:
    serviceMonitor:
      additionalLabels:
        prometheus: prometheus
    prometheusSpec:
      retention: 30d
      # storageSpec: 
      #   volumeClaimTemplate:
      #     spec:
      #       accessModes: ["ReadWriteOnce"]
      #       resources:
      #         requests:
      #           storage: 10Gi
      serviceMonitorSelector:
        matchLabels:
          prometheus: prometheus

  prometheus-node-exporter:
    serviceMonitor:
      additionalLabels:
        prometheus: prometheus

  kube-state-metrics:
    serviceMonitor:
      additionalLabels:
        prometheus: prometheus

  kubeScheduler:
    serviceMonitor:
      additionalLabels:
        prometheus: prometheus

  kubernetesServiceMonitors:
    serviceMonitor:
      additionalLabels:
        prometheus: prometheus

  kubeControllerManager:
    serviceMonitor:
      additionalLabels:
        prometheus: prometheus

  kubeApiServer:
    serviceMonitor:
      additionalLabels:
        prometheus: prometheus

  kubelet:
    serviceMonitor:
      additionalLabels:
        prometheus: prometheus

  coreDns:
    serviceMonitor:
      additionalLabels:
        prometheus: prometheus

  kubeDns:
    serviceMonitor:
      additionalLabels:
        prometheus: prometheus

  kubeEtcd:
    serviceMonitor:
      additionalLabels:
        prometheus: prometheus

  kubeScheduler:
    serviceMonitor:
      additionalLabels:
        prometheus: prometheus

  kubeProxy:
    serviceMonitor:
      additionalLabels:
        prometheus: prometheus

  kubeletService:
    serviceMonitor:
      additionalLabels:
        prometheus: prometheus
