apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingresspublic
spec:
  project: default
  source:
    repoURL: 'git@github.com:politeauthority/olive-iron.git'
    path: services/ingress-public
    targetRevision: intial-apps
    helm:
      valueFiles:
        - values-olive-iron.yaml
  destination:
    namespace: ingress-public
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
