apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metricsserver
spec:
  project: default
  source:
    repoURL: 'git@github.com:politeauthority/olive-iron.git'
    path: services/metrics-server
    targetRevision: main
  destination:
    namespace: kube-system
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
