# Prometheus Stack
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheusstack
spec:
  project: default
  source:
    repoURL: 'git@github.com:politeauthority/olive-iron.git'
    path: services/prometheus-stack/
    targetRevision: monitoring
    helm:
      valueFiles:
        - values-olive-iron.yaml
  sources: []
  destination:
    namespace: monitoring
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
